### PR TITLE
AMD and CommonJS support, Updated to 1.4.0

### PR DESCRIPTION
**Pull request by aeksco**
Adds support for AMD and CommonJS module loading - tested with Browserify, should also work with WebPack. 

**Changes:**
- Updated `README.md` release history.
- Updated `package.json` version.
- Added `'ParticleNetwork'` & `'exports'` to `mangleExceptions.json`.
- Trailing whitespace removed.

**Notes:**
- `demo.html` working with both `particle-network.js` and `particle-network.min.js`.
- Passing `grunt eslint`.

### CODE REVIEW

**Comment by JulianLaval** [comment]
Great stuff! Will take a look ASAP :)

**Comment by tasarsu** [comment]
Thank you both!
I have used your pr in webpack it works. But if we could pass this to a variable it would be superb.
- Now we have to use as

``` javascript
require('canvas-particle-network')
// and ParticleNetwork automatically works
var particleCanvas = new ParticleNetwork(canvasDiv, options);
```
- for some possible conflicts it would be nice if we can 

``` javascript
var pn = require('canvas-particle-network')
var particleCanvas = new pn(canvasDiv, options);
```

**Comment by aeksco** [comment]
@tasarsu Happy to hear it works in Webpack :)

I _believe_ that it can be assigned to a variable like you listed above:

``` js
var pn = require('canvas-particle-network')
var particleCanvas = new pn(canvasDiv, options);
```

However, I am unsure if it assigns it to a variable _in addition_ to instantiating the global `ParticleNetwork` reference.

I'll check my code sometime tomorrow and confirm. Excited to get this merged in!

**Comment by aeksco** [comment]
**Update:**

The code in this PR does assign it to a variable without also creating a global `ParticleNetwork` reference. My implementation is as follows:

``` coffee
pn = require 'canvas-particle-network'

$(document).on 'ready', =>

  particleCanvas = new pn($('[data-canvas=particles]')[0], options)

  console.log ParticleNetwork # undefined
```

If there aren't any other questions I would love to get this merged in. There are a few features that I would like to open separate PRs for soon :)

**Comment by JulianLaval** [comment]
Merged - sorry for the delay, and thanks for the PR!

Looking forward to any other features you might have in mind :)

**Comment by aeksco** [comment]
@JulianLaval No worries! Thanks for the merge - looking forward to ongoing development :D

**Pull request merged**
